catalog:
  "@antfu/eslint-config": ^4.1.0
  "@eslint/compat": ^1.2.5
  "@eslint-react/eslint-plugin": ^1.25.0
  "@mui/types": ^7.2.21
  "@types/eslint-config-prettier": ^6.11.3
  "@types/react": ^19.0.8
  es-toolkit: ^1.31.0
  eslint: ^9.19.0
  eslint-config-prettier: ^10.0.1
  eslint-flat-config-utils: ^2.0.0
  eslint-plugin-mdx: ^3.1.5
  eslint-plugin-package-json: ^0.21.1
  eslint-plugin-react-compiler: ^19.0.0-beta-27714ef-20250124
  eslint-plugin-react-hooks: ^5.1.0
  eslint-plugin-react-refresh: ^0.4.18
  eslint-plugin-storybook: ^0.11.2
  eslint-plugin-svelte: ^2.46.1
  local-pkg: ^1.0.0
  svelte: ^5.19.4
  typescript: ^5.7.3
packages:
  - "packages/*"
